[package]
name = "wtlocale"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.12"
rfd = "0.15"
regex = "1.11"
rustring_builder = "0.2"
arboard = "3.6"
opener = "0.8"
csv = "1.3"

[build-dependencies]
slint-build = "1.12"
