import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component GameFolderSelector inherits Window {
    in-out property <string> selected-folder-text: "";
    callback request-file-dialog-open();

    min-width: 720px;
    min-height: 480px;

    VerticalBox {
        Text {
            text: "Выберите каталог с игрой";
            font-size: 24px;
        }

        HorizontalBox {
            height: 42px;
            LineEdit {
                text: selected-folder-text;
                enabled: false;
            }
            Button {
                text: "Выбрать";
                width: 100px;
                clicked => {
                    request-file-dialog-open()
                }
            }
        }
    }
}
