import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component GameFolderSelectorUI inherits Window {
    in property <string> error;
    in property <string> selected-folder-text;
    in property <bool> continuation-allowed: false;
    callback request-file-dialog-open();
    callback request-continue();

    min-width: 320px;
    min-height: 144px;
    title: "Выбор каталога";
    icon: @image-url("../assets/icon.png");

    VerticalBox {
        alignment: space-between;
        Text {
            text: "Выберите каталог с игрой";
            font-size: 2rem;
        }

        VerticalBox {
            HorizontalBox {
                LineEdit {
                    text: selected-folder-text;
                    enabled: false;
                }

                Button {
                    text: "Выбрать";
                    clicked => {
                        request-file-dialog-open()
                    }
                }
            }

            HorizontalBox {
                alignment: end;

                Text {
                    text: error;
                    color: red;
                    font-size: 16px;
                }

                Button {
                    text: "Продолжить";
                    enabled: continuation-allowed;
                    clicked => {
                        request-continue()
                    }
                }
            }
        }
    }
}
